language: python
python:
  - "2.7"
  - pypy
install:
  - pip install --editable .
before_script:
  - pip install python-coveralls pytest-cov
script: py.test --cov=swga swga
after_success:
  - coveralls