language: python
python:
  - "2.7"
install:
  - "pip install ."
before_script:
  - pip install python-coveralls pytest-cov
script: py.test --cov=swga --cov-config tests/.coveragerc
after_success:
  - coveralls