language: python
python:
  - "2.7"
  - pypy
install:
  - pip install --editable .
before_script:
  - pip install python-coveralls pytest-cov
script:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then py.test --cov=swga swga; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test swga; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
